# Generated by Django 4.2.5 on 2023-09-24 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_banned',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_activity',
        ),
        migrations.DeleteModel(
            name='ReportedUsers',
        ),
    ]
